"programMyTokens": {
    "addCrmCampaign": "Agregar campaña de CRM",
    "addDate": "Agregar fecha",
    "addLink": "Agregar vínculo",
    "addNumber": "Agregar número",
    "linkTrackingExplanation": "El vínculo de seguimiento e incluir mkt_tok solo son aplicables cuando en vínculo MyToken se utiliza en un correo electrónico",
    "addScript": "Agregar script",
    "addScore": "Agregar puntaje",
    "addScoreExample": "+20, -5, = 50 y así sucesivamente",
    "addText": "Agregar texto",
    "assetSingular": "Recurso",
    "assetPlural": "Recursos",
    "calendarToken": "Token de archivo de calendario",
    "chooseCrmCampaign": "Elegir campaña de CRM",
    "createFolder": "Crear carpeta",
    "createGoogleLink": "Crear vínculo de Google",
    "sfdc campaign": "campaña de crm",
    "crmCampaignRequired": "La campaña de CRM es obligatoria",
    "crmCampaignToken": "Token de campaña de CRM",
    "custom": "Personalizar",
    "date": "fecha",
    "dateRequired": "La fecha es obligatoria",
    "dateToken": "Token de fecha",
    "dragAndDropDetails": "tokens aquí de la lista de la derecha.",
    "dragAndDropTitle": "Arrastrar y soltar",
    "delete": "Eliminar",
    "deleteToken": "Eliminar token",
    "deleteTokenFolder": "Eliminar la carpeta del token",
    "description": "Descripción",
    "endDate": "Fecha de finalización",
    "endDateRequired": "Ingrese la fecha de finalización",
    "endDateHigherThanStartDate": "La fecha de finalización debe ser posterior a la fecha de inicio.",
    "findUsages": "Encontrar usos",
    "folderName": "Nombre de la carpeta",
    "help": "Ayuda",
    "hyperlinkText": "Texto del hipervínculo",
    "hyperlinkTextRequired": "Ingrese el texto del hipervínculo",
    "iCalendar": "Archivo de calendario",
    "image": "imagen",
    "import": "Importar",
    "inheritedTokens": "Tokens heredados",
    "lastModified": "Última modificación",
    "link": "vínculo",
    "linkRequired": "Ingrese el vínculo",
    "linkToken": "Token de vínculo",
    "localTokens": "Tokens locales",
    "location": "Ubicación",
    "locationRequired": "Ingrese el lugar",
    "makeLinkTrackable": "Hacer que el vínculo sea rastreable",
    "newTokenFolder": "Nueva carpeta de tokens",
    "noDetectedUsage": "No se encontró ningún uso para {0}",
    "number": "Número",
    "numberRequired": "Ingrese el número",
    "numberToken": "Token de número",
    "overriddenTokens": "Tokens anulados",
    "reminder": "Recordatorio",
    "rich text": "Texto enriquecido",
    "scriptToken": "Token de script",
    "score": "Puntaje",
    "scoreRequired": "Ingrese el puntaje",
    "scoreToken": "Token de puntaje",
    "script block": "Script de correo electrónico",
    "search": "Buscar",
    "subject": "Asunto",
    "subjectRequired": "Ingrese el asunto",
    "standard": "Estándar",
    "startDate": "Fecha de inicio",
    "startDateLowerThanEndDate": "La fecha de inicio debe ser inferior a la fecha de finalización.",
    "startDateRequired": "Ingrese la fecha de inicio",
    "text": "texto",
    "textRequired": "Ingrese el texto",
    "textToken": "Token de texto",
    "tokenFolderNameRequired": "Ingrese el nombre de la carpeta",
    "token": "Token",
    "tokenFolder": "Carpeta del token",
    "tokenPlural": "Tokens",
    "tokenSingular": "Token",
    "tokenTypes": "Tipos de token",
    "tokenName": "Nombre",
    "tokenNameRequired": "Ingrese el nombre del token",
    "invalidTokenName": "Los nombres de tokens están limitados a utilizar caracteres alfanuméricos, espacios y (&#_-)",
    "tokenSectionRequired": "Ingrese el tipo",
    "tokenUsage": "Uso del token",
    "tokenUsageInformation": "{0} se usa en {1} {2}",
    "cannotDeleteTokenMessage": "{0} no puede eliminarse porque se está usando en {1} {2}",
    "renameTokenFolder": "Cambiar nombre de la carpeta del token",
    "richTextToken": "Token de texto enriquecido",
    "type": "Tipo",
    "value": "Valor",
    "copyTokenName": "Copiar nombre de token",
    "edit": "Editar",
    "moveToFolder": "Mover a carpeta",
    "rename": "Cambiar nombre",
    "clone": "Clonar",
    "createNew": "Crear nuevo",
    "landingPage": "Landing Page"
  };