"programMyTokens": {
    "addCrmCampaign": "Ajouter une campagne CRM",
    "addDate": "Ajouter une date",
    "addLink": "Ajouter un lien",
    "addNumber": "Ajouter un numéro",
    "linkTrackingExplanation": "Lien de tracking et Inclure mkt_tok ne sont applicables que lorsque le lien MyToken est utilisé dans un e-mail",
    "addScript": "Ajouter un script",
    "addScore": "Ajouter un score",
    "addScoreExample": "+20, -5, = 50, etc",
    "addText": "Ajouter un texte",
    "assetSingular": "Ressource",
    "assetPlural": "Ressources",
    "calendarToken": "Jeton de fichier de calendrier",
    "chooseCrmCampaign": "Choisir une campagne CRM",
    "createFolder": "Créer un dossier",
    "createGoogleLink": "Créer un lien Google",
    "sfdc campaign": "campagne crm",
    "crmCampaignRequired": "Campagne CRM requise",
    "crmCampaignToken": "Jeton de campagne CRM",
    "custom": "Personnaliser",
    "date": "date",
    "dateRequired": "Date requise",
    "dateToken": "Jeton date",
    "dragAndDropDetails": "des jetons ici depuis la liste de droite.",
    "dragAndDropTitle": "Glisser et déposer",
    "delete": "Supprimer",
    "deleteToken": "Supprimer jeton",
    "deleteTokenFolder": "Supprimer le dossier de jeton",
    "description": "Description",
    "endDate": "Date de fin",
    "endDateRequired": "Saisissez une date de fin",
    "endDateHigherThanStartDate": "La date de fin doit être ultérieure à la date de début.",
    "findUsages": "Trouver des utilisations",
    "folderName": "Nom de dossier",
    "help": "Aide",
    "hyperlinkText": "Texte du lien hypertexte",
    "hyperlinkTextRequired": "Saisissez le lien hypertexte",
    "iCalendar": "Fichier du calendrier",
    "image": "Image",
    "import": "Importer",
    "inheritedTokens": "Jetons transmis",
    "lastModified": "Dernière modification",
    "link": "lien",
    "linkRequired": "Saisissez un lien",
    "linkToken": "Jeton de lien",
    "localTokens": "Jetons locaux",
    "location": "Localisation",
    "locationRequired": "Saisissez un emplacement",
    "makeLinkTrackable": "Ajouter la traçabilité du lien",
    "newTokenFolder": "Nouveau dossier de jeton",
    "noDetectedUsage": "Aucune utilisation détectée pour {0}",
    "number": "Nombre",
    "numberRequired": "Saisissez un numéro",
    "numberToken": "Jeton de numéro",
    "overriddenTokens": "Jetons ignorés",
    "reminder": "Rappel",
    "rich text": "Texte complet",
    "scriptToken": "Jeton de script",
    "score": "Évaluation",
    "scoreRequired": "Saisissez un score",
    "scoreToken": "Jeton de score",
    "script block": "Script de l'e-mail",
    "search": "Rechercher",
    "subject": "Objet",
    "subjectRequired": "Saisissez un objet",
    "standard": "Standard",
    "startDate": "Date de début",
    "startDateLowerThanEndDate": "La date de début doit être antérieure à la date de fin.",
    "startDateRequired": "Saisissez une date de début",
    "text": "Texte",
    "textRequired": "Saisissez un texte",
    "textToken": "Jeton de texte",
    "tokenFolderNameRequired": "Saisissez un nom de dossier",
    "token": "Jeton",
    "tokenFolder": "Dossier de jeton",
    "tokenPlural": "Jetons",
    "tokenSingular": "Jeton",
    "tokenTypes": "Types de jetons",
    "tokenName": "Nom",
    "tokenNameRequired": "Saisissez un nom de jeton",
    "invalidTokenName": "Les noms de jetons doivent comprendre seulement des caractères alphanumériques, des espaces et (&#_-)",
    "tokenSectionRequired": "Saisissez un type",
    "tokenUsage": "Utilisation de jeton",
    "tokenUsageInformation": "{0} est utilisé dans {1} {2}",
    "cannotDeleteTokenMessage": "{0} ne peut pas être supprimé, car il est utilisé dans {1} {2}",
    "renameTokenFolder": "Renommer le dossier de jeton",
    "richTextToken": "Jeton de texte riche",
    "type": "Type",
    "value": "Valeur",
    "copyTokenName": "Copier le nom de jeton",
    "edit": "Modifier",
    "moveToFolder": "Déplacer vers le dossier",
    "rename": "Renommer",
    "clone": "Cloner",
    "createNew": "Créer nouveau",
    "landingPage": "Landing Page"
  };