"programMyTokens": {
    "addCrmCampaign": ":Add CRM Campaign:",
    "addDate": ":Add Date:",
    "addLink": ":Add Link:",
    "addNumber": ":Add Number:",
    "linkTrackingExplanation": ":Track Link and Inlcude mkt_tok are only applicable when the Link MyToken is used in an email:",
    "addScript": ":Add Script:",
    "addScore": ":Add Score:",
    "addScoreExample": ":+20, -5, =50, and so on:",
    "addText": ":Add Text:",
    "assetSingular": ":asset:",
    "assetPlural": ":assets:",
    "calendarToken": ":Calendar File Token:",
    "chooseCrmCampaign": ":Choose CRM Campaign:",
    "createFolder": ":Create Folder:",
    "createGoogleLink": ":Create Google Link:",
    "sfdc campaign": ":crm campaign:",
    "crmCampaignRequired": ":CRM Campaign Required:",
    "crmCampaignToken": ":CRM Campaign Token:",
    "custom": ":Custom:",
    "date": ":date:",
    "dateRequired": ":Date Required:",
    "dateToken": ":Date Token:",
    "dragAndDropDetails": ":tokens here from the list on the right:.",
    "dragAndDropTitle": ":Drag & Drop:",
    "delete": ":Delete:",
    "deleteToken": ":Delete Token:",
    "deleteTokenFolder": ":Delete Token Folder:",
    "description": ":Description:",
    "endDate": ":End Date:",
    "endDateRequired": ":Please Enter End Date:",
    "endDateHigherThanStartDate": ":End date must be higher than start date:.",
    "findUsages": ":Find Usages:",
    "folderName": ":Folder Name:",
    "help": ":Help:",
    "hyperlinkText": ":Hyperlink Text:",
    "hyperlinkTextRequired": ":Please Enter Hyperlink Text:",
    "iCalendar": ":calendar file:",
    "image": ":image:",
    "import": ":Import:",
    "inheritedTokens": ":Inherited Tokens:",
    "lastModified": ":Last Modified:",
    "link": ":link:",
    "linkRequired": ":Please Enter Link:",
    "linkToken": ":Link Token:",
    "localTokens": ":Local Tokens:",
    "location": ":Location:",
    "locationRequired": ":Please Enter Location:",
    "makeLinkTrackable": ":Make Link Trackable:",
    "newTokenFolder": ":New Token Folder:",
    "noDetectedUsage": ":No detected usage for {0}:",
    "number": ":number:",
    "numberRequired": ":Please Enter Number:",
    "numberToken": ":Number Token:",
    "overriddenTokens": ":Overridden Tokens:",
    "reminder": ":Reminder:",
    "rich text": ":rich text:",
    "scriptToken": ":Script Token:",
    "score": ":score:",
    "scoreRequired": ":Please Enter Score:",
    "scoreToken": ":Score Token:",
    "script block": ":Email Script:",
    "search": ":SEARCH:",
    "subject": ":Subject:",
    "subjectRequired": ":Please Enter Subject:",
    "standard": ":Standard:",
    "startDate": ":Start Date:",
    "startDateLowerThanEndDate": ":Start date must be lower than end date:.",
    "startDateRequired": ":Please Enter Start Date:",
    "text": ":text:",
    "textRequired": ":Please Enter Text:",
    "textToken": ":Text Token:",
    "tokenFolderNameRequired": ":Please Enter Folder Name:",
    "token": ":Token:",
    "tokenFolder": ":Token Folder:",
    "tokenPlural": ":Tokens:",
    "tokenSingular": ":Token:",
    "tokenTypes": ":Token Types:",
    "tokenName": ":Name:",
    "tokenNameRequired": ":Please Enter Token Name:",
    "invalidTokenName": ":Token names limited to alpha numeric characters, spaces, and (&#_-):",
    "tokenSectionRequired": ":Please Enter Type:",
    "tokenUsage": ":Token Usage:",
    "tokenUsageInformation": ":{0} is used in {1} {2}:",
    "cannotDeleteTokenMessage": ":{0} cannot be deleted because it is being used in {1} {2}:",
    "renameTokenFolder": ":Rename Token Folder:",
    "richTextToken": ":Rich Text Token:",
    "type": ":Type:",
    "value": ":Value:",
    "copyTokenName": ":Copy Token Name:",
    "edit": ":Edit:",
    "moveToFolder": ":Move to Folder:",
    "rename": ":Rename:",
    "clone": ":Clone:",
    "createNew": ":Create New:"
  };