"programMyTokens": {
    "addCrmCampaign": "CRM キャンペーンの追加",
    "addDate": "日付の追加",
    "addLink": "リンクの追加",
    "addNumber": "番号の追加",
    "linkTrackingExplanation": "トラッキングリンクと「mkt_tok を含む」は、「マイトークンをリンク」がメールで使用されているときにのみ利用可能です",
    "addScript": "スクリプトの追加",
    "addScore": "スコアの追加",
    "addScoreExample": "+20、-5、=50 など",
    "addText": "テキストの追加",
    "assetSingular": "アセット",
    "assetPlural": "アセット",
    "calendarToken": "カレンダーファイルトークン",
    "chooseCrmCampaign": "CRM キャンペーンの選択",
    "createFolder": "フォルダの作成",
    "createGoogleLink": "Google リンクの作成",
    "sfdc campaign": "crm キャンペーン",
    "crmCampaignRequired": "CRM キャンペーンが必要です",
    "crmCampaignToken": "CRM キャンペーントークン",
    "custom": "カスタム",
    "date": "日",
    "dateRequired": "日付が必要です",
    "dateToken": "日付トークン",
    "dragAndDropDetails": "トークンを右のリストからここに",
    "dragAndDropTitle": "ドラッグ＆ドロップ",
    "delete": "削除",
    "deleteToken": "トークンの削除",
    "deleteTokenFolder": "トークンフォルダを削除",
    "description": "詳細",
    "endDate": "終了日",
    "endDateRequired": "終了日を入力してください",
    "endDateHigherThanStartDate": "終了日は開始日より後でなければなりません",
    "findUsages": "使用を検索",
    "folderName": "フォルダ名",
    "help": "ヘルプ",
    "hyperlinkText": "ハイパーリンク",
    "hyperlinkTextRequired": "ハイパーリンクテキストを入力してください",
    "iCalendar": "カレンダーファイル",
    "image": "画像",
    "import": "インポート",
    "inheritedTokens": "引き継いだトークン",
    "lastModified": "最終変更日",
    "link": "リンク",
    "linkRequired": "リンクを入力してください",
    "linkToken": "リンクトークン",
    "localTokens": "ローカルトークン",
    "location": "ロケーション",
    "locationRequired": "ロケーションを入力してください",
    "makeLinkTrackable": "リンクを追跡可能にする",
    "newTokenFolder": "新規トークンフォルダ",
    "noDetectedUsage": "{0} の使用が検出されません",
    "number": "数字",
    "numberRequired": "番号を入力してください",
    "numberToken": "番号トークン",
    "overriddenTokens": "上書きされたトークン",
    "reminder": "リマインダ",
    "rich text": "リッチ テキスト",
    "scriptToken": "スクリプトトークン",
    "score": "スコア",
    "scoreRequired": "スコアを入力してください",
    "scoreToken": "スコアトークン",
    "script block": "メールスクリプト",
    "search": "検索",
    "subject": "件名",
    "subjectRequired": "件名を入力してください",
    "standard": "標準",
    "startDate": "開始日",
    "startDateLowerThanEndDate": "開始日は終了日より先でなければなりません。",
    "startDateRequired": "開始日を入力してください",
    "text": "テキスト",
    "textRequired": "テキストを入力してください",
    "textToken": "テキストトークン",
    "tokenFolderNameRequired": "フォルダ名を入力してください",
    "token": "トークン",
    "tokenFolder": "トークンフォルダ",
    "tokenPlural": "トークン",
    "tokenSingular": "トークン",
    "tokenTypes": "トークンのタイプ",
    "tokenName": "名前",
    "tokenNameRequired": "トークン名を入力してください",
    "invalidTokenName": "トークン名は英数文字、スペース、(&#_-) に制限されています",
    "tokenSectionRequired": "タイプを入力してください",
    "tokenUsage": "トークン使用",
    "tokenUsageInformation": "{0} は {1} {2} で使用されています",
    "cannotDeleteTokenMessage": "{0} は {1} {2} で使用されているため削除できません",
    "renameTokenFolder": "トークンフォルダ名を変更",
    "richTextToken": "リッチテキストトークン",
    "type": "タイプ",
    "value": "値",
    "copyTokenName": "トークン名のコピー",
    "edit": "編集",
    "moveToFolder": "フォルダに移動",
    "rename": "名前変更",
    "clone": "複製",
    "createNew": "新規作成"
  };