Mkt3L10n.lobEditor = {
    Submit: "Submit",
    Clear: "Clear",
    Are_you_sure_you_want_delete_arg0: "Are you sure you want to delete <b>{0}</b>?",
    Change_requires_browser_refresh: "Change requires a browser refresh",
    Delete_Field: "Delete Field",
    Edit_Del: "Click to edit or delete, or drag to reorder form fields",
    Editor_Active: "editor is not active",
    No_Changes: "No changes to save",
    No_Field_Property: "No field is selected. Cannot change properties.",
    No_Profields: "Number of Profiling Fields must be a number between 1 and 10",
    Not_Field_Server: "Did not find a new field for every new ID from the server",
    Not_implemented: "Not implemented",
    Please_wait_for_refresh: "Wait for refresh",
    Refresh_Browser: "Refresh the browser to see the change",
    Save: "Save",
    Ok: "OK",
    Setthe_Source_Value_Hidden_Field: "Set the Source for the Value of this Hidden Field",
    Setup_progressive_profiling: "Set up progressive profiling for the form",
    btn_notfunction: "This button does not function when you click it inside the editor.",
    disabled: "disabled...",
    Label_above_input_field_aligned_edge: "Label above the input field and aligned with its left edge",
    Label_left_side_input_fields_labels_left_lined: "Label to the left side of the input fields and with the labels left edges lined up",
    Label_left_side_input_fields_labels_right_lined: "Label to the left side of the input fields and with the labels right edges lined up",
    Name: "Name",
    name_of_this_form: "name of this form",
    Description: "Description",
    your_noteson_this_form: "your notes on this form",
    How_the_labels_and_fields_are_arranged_in_this_form: "How the labels and fields are arranged in this form",
    Discount: "Discount",
    Hello: "Hello",
    Files: "Files",
    Store: "Store",
    Banner: "Banner",
    Statistic: "Statistic",
    List: "List",
    Last: "Last",
    Home: "Home",
    Sales : "Sales",
    Mobile: "Mobile",
    Page: "User Page",
    Logs: "Logs",
    Template: "Template"
};  

