"programMyTokens": {
    "addCrmCampaign": "Adicionar campanha de CRM",
    "addDate": "Adicionar data",
    "addLink": "Adicionar link",
    "addNumber": "Adicionar número",
    "linkTrackingExplanation": "Acompanhar link e incluir mkt_tok só se aplicam se o link MyToken for usado num e-mail",
    "addScript": "Adicionar script",
    "addScore": "Adicionar pontuação",
    "addScoreExample": "+20, -5, =50 e assim por diante",
    "addText": "Adicionar texto",
    "assetSingular": "Ativo",
    "assetPlural": "Ativos",
    "calendarToken": "Token de arquivo do calendário",
    "chooseCrmCampaign": "Escolher campanha de CRM",
    "createFolder": "Criar pasta",
    "createGoogleLink": "Criar link do Google",
    "sfdc campaign": "campanha de CRM",
    "crmCampaignRequired": "Campanha de CRM obrigatória",
    "crmCampaignToken": "Token de campanha de CRM",
    "custom": "Personalizado",
    "date": "data",
    "dateRequired": "Data obrigatória",
    "dateToken": "Token de data",
    "dragAndDropDetails": "tokens aqui na lista à direita.",
    "dragAndDropTitle": "Arrastar e soltar",
    "delete": "Excluir",
    "deleteToken": "Excluir token",
    "deleteTokenFolder": "Excluir pasta do token",
    "description": "Descrição",
    "endDate": "Data final",
    "endDateRequired": "Insira a data de término",
    "endDateHigherThanStartDate": "A data de término deve ser posterior à de início.",
    "findUsages": "Localizar utilizações",
    "folderName": "Nome da pasta",
    "help": "Ajuda",
    "hyperlinkText": "Texto do hiperlink",
    "hyperlinkTextRequired": "Insira o texto do link",
    "iCalendar": "Arquivo de calendário",
    "image": "imagem",
    "import": "Importar",
    "inheritedTokens": "Tokens herdados",
    "lastModified": "Última modificação",
    "link": "link",
    "linkRequired": "Insira o link",
    "linkToken": "Token do link",
    "localTokens": "Tokens do local",
    "location": "Local",
    "locationRequired": "Insira o local",
    "makeLinkTrackable": "Tornar o link rastreável",
    "newTokenFolder": "Nova pasta de tokens",
    "noDetectedUsage": "Nenhuma utilização detectada para {0}",
    "number": "Número",
    "numberRequired": "Insira o número",
    "numberToken": "Token do número",
    "overriddenTokens": "Tokens substituídos",
    "reminder": "Lembrete",
    "rich text": "Texto formatado",
    "scriptToken": "Token de script",
    "score": "Pontuação",
    "scoreRequired": "Insira a pontuação",
    "scoreToken": "Token da pontuação",
    "script block": "Script de e-mail",
    "search": "Pesquisar",
    "subject": "Assunto",
    "subjectRequired": "Insira o assunto",
    "standard": "Padrão",
    "startDate": "Data de início",
    "startDateLowerThanEndDate": "A data de início deve ser anterior à data de término.",
    "startDateRequired": "Insira a data de início",
    "text": "texto",
    "textRequired": "Insira o texto",
    "textToken": "Token do texto",
    "tokenFolderNameRequired": "Insira o nome da pasta",
    "token": "Token",
    "tokenFolder": "Pasta do token",
    "tokenPlural": "Tokens",
    "tokenSingular": "Token",
    "tokenTypes": "Tipos de token",
    "tokenName": "Nome",
    "tokenNameRequired": "Insira o nome do token",
    "invalidTokenName": "Os nomes de tokens limitam-se a caracteres alfanuméricos, espaços e (&#_-)",
    "tokenSectionRequired": "Insira o tipo",
    "tokenUsage": "Utilização do token",
    "tokenUsageInformation": "{0} é usado em {1} {2}",
    "cannotDeleteTokenMessage": "Não é possível excluir {0} porque está em uso em {1} {2}",
    "renameTokenFolder": "Renomear pasta do token",
    "richTextToken": "Token de Rich Text",
    "type": "Tipo",
    "value": "Valor",
    "copyTokenName": "Copiar nome do token",
    "edit": "Editar",
    "moveToFolder": "Mover para a pasta",
    "rename": "Renomear",
    "clone": "Clonar",
    "createNew": "Criar novo",
    "landingPage": "Landing Page"
  };